// 80문제: 한국사, 과학, 지리, 스포츠 각 20문제
const QUESTIONS = [
  // ===== 한국사 =====
  {
    id: 1,
    category: "한국사",
    difficulty: "easy",
    question: "조선을 건국한 왕은?",
    options: ["이성계", "왕건", "이방원", "세종"],
    correctAnswer: 0,
    explanation: "이성계는 1392년 조선을 건국했습니다.",
  },
  {
    id: 2,
    category: "한국사",
    difficulty: "easy",
    question: "고려를 건국한 인물은?",
    options: ["궁예", "왕건", "견훤", "김유신"],
    correctAnswer: 1,
    explanation: "왕건은 918년 고려를 건국했습니다.",
  },
  {
    id: 3,
    category: "한국사",
    difficulty: "easy",
    question: "훈민정음(한글)을 창제한 조선의 왕은?",
    options: ["태종", "세종", "정조", "영조"],
    correctAnswer: 1,
    explanation: "세종대왕은 1443년 훈민정음을 창제했습니다.",
  },
  {
    id: 4,
    category: "한국사",
    difficulty: "medium",
    question: "임진왜란이 시작된 연도는?",
    options: ["1392년", "1592년", "1636년", "1876년"],
    correctAnswer: 1,
    explanation: "임진왜란은 1592년 일본의 조선 침략으로 시작되었습니다.",
  },
  {
    id: 5,
    category: "한국사",
    difficulty: "medium",
    question: "3·1 운동이 일어난 연도는?",
    options: ["1910년", "1919년", "1926년", "1945년"],
    correctAnswer: 1,
    explanation: "3·1 운동은 1919년 3월 1일 일제강점기에 일어난 독립운동입니다.",
  },
  {
    id: 6,
    category: "한국사",
    difficulty: "medium",
    question: "1919년 대한민국 임시정부가 수립된 도시는?",
    options: ["도쿄", "베이징", "상하이", "블라디보스토크"],
    correctAnswer: 2,
    explanation: "대한민국 임시정부는 1919년 중국 상하이에서 수립되었습니다.",
  },
  {
    id: 7,
    category: "한국사",
    difficulty: "medium",
    question: "광개토대왕은 어느 나라의 왕이었는가?",
    options: ["백제", "신라", "고구려", "가야"],
    correctAnswer: 2,
    explanation: "광개토대왕(재위 391~412)은 고구려의 왕으로 영토를 크게 넓혔습니다.",
  },
  {
    id: 8,
    category: "한국사",
    difficulty: "medium",
    question: "훈민정음이 반포된 연도는?",
    options: ["1443년", "1446년", "1450년", "1592년"],
    correctAnswer: 1,
    explanation: "훈민정음은 1443년 창제되어 1446년에 반포되었습니다.",
  },
  {
    id: 9,
    category: "한국사",
    difficulty: "hard",
    question: "신라가 삼국통일을 완성한(676년) 당시의 왕은?",
    options: ["무열왕", "문무왕", "선덕여왕", "진흥왕"],
    correctAnswer: 1,
    explanation: "문무왕은 676년 나당전쟁에서 승리하며 삼국통일을 완성했습니다.",
  },
  {
    id: 10,
    category: "한국사",
    difficulty: "easy",
    question: "6·25 전쟁(한국전쟁)이 발발한 연도는?",
    options: ["1945년", "1950년", "1953년", "1961년"],
    correctAnswer: 1,
    explanation: "6·25 전쟁은 1950년 6월 25일 북한의 남침으로 시작되었습니다.",
  },
  {
    id: 41,
    category: "한국사",
    difficulty: "medium",
    question: "병자호란이 발발한 연도는?",
    options: ["1592년", "1610년", "1627년", "1636년"],
    correctAnswer: 3,
    explanation: "병자호란은 1636년 청나라(후금)가 조선을 침략하며 시작된 전쟁입니다.",
  },
  {
    id: 42,
    category: "한국사",
    difficulty: "easy",
    question: "임진왜란 당시 거북선을 이용해 일본 수군을 크게 무찌른 조선의 장군은?",
    options: ["이순신", "권율", "신립", "김시민"],
    correctAnswer: 0,
    explanation: "이순신 장군은 임진왜란 때 거북선과 학익진 전법 등으로 일본 수군을 여러 차례 크게 격파했습니다.",
  },
  {
    id: 43,
    category: "한국사",
    difficulty: "easy",
    question: "고구려를 건국한 인물은?",
    options: ["온조", "박혁거세", "김수로", "주몽"],
    correctAnswer: 3,
    explanation: "주몽(동명성왕)은 기원전 37년 고구려를 건국했습니다.",
  },
  {
    id: 44,
    category: "한국사",
    difficulty: "easy",
    question: "신라를 건국한 인물은?",
    options: ["박혁거세", "온조", "주몽", "김수로"],
    correctAnswer: 0,
    explanation: "박혁거세는 기원전 57년 신라(사로국)를 건국했다고 전해집니다.",
  },
  {
    id: 45,
    category: "한국사",
    difficulty: "medium",
    question: "세종 재위 시기 만들어진, 강우량(빗물의 양)을 측정하는 기구는?",
    options: ["자격루", "앙부일구", "측우기", "혼천의"],
    correctAnswer: 2,
    explanation: "측우기는 세종 재위 시기(1441년경) 만들어진 강우량 측정 기구입니다.",
  },
  {
    id: 46,
    category: "한국사",
    difficulty: "medium",
    question: "강화도조약이 체결된 연도는?",
    options: ["1863년", "1871년", "1875년", "1876년"],
    correctAnswer: 3,
    explanation: "강화도조약은 1876년 조선과 일본 사이에 체결된 조약입니다.",
  },
  {
    id: 47,
    category: "한국사",
    difficulty: "medium",
    question: "6·25 전쟁의 정전협정이 체결된 연도는?",
    options: ["1953년", "1950년", "1948년", "1961년"],
    correctAnswer: 0,
    explanation: "6·25 전쟁 정전협정은 1953년 7월 27일 체결되었습니다.",
  },
  {
    id: 48,
    category: "한국사",
    difficulty: "medium",
    question: "대한제국을 선포하며 초대 황제로 즉위한 인물은?",
    options: ["순종", "철종", "고종", "정조"],
    correctAnswer: 2,
    explanation: "고종은 1897년 대한제국을 선포하고 초대 황제로 즉위했습니다.",
  },
  {
    id: 49,
    category: "한국사",
    difficulty: "hard",
    question: "다산 정약용이 저술한, 지방관(목민관)의 도리를 다룬 책은?",
    options: ["경국대전", "동의보감", "반계수록", "목민심서"],
    correctAnswer: 3,
    explanation: "목민심서는 정약용이 지방관의 통치 지침을 담아 저술한 책입니다.",
  },
  {
    id: 50,
    category: "한국사",
    difficulty: "medium",
    question: "고구려 멸망 이후 고구려 유민 등을 이끌고 발해를 건국한 인물은?",
    options: ["대조영", "온조", "견훤", "궁예"],
    correctAnswer: 0,
    explanation: "대조영은 698년 고구려 유민과 말갈족을 이끌고 발해를 건국했습니다.",
  },

  // ===== 과학 =====
  {
    id: 11,
    category: "과학",
    difficulty: "easy",
    question: "물의 화학식은?",
    options: ["CO2", "H2O", "O2", "NaCl"],
    correctAnswer: 1,
    explanation: "물은 수소 원자 2개와 산소 원자 1개로 이루어진 H2O입니다.",
  },
  {
    id: 12,
    category: "과학",
    difficulty: "easy",
    question: "태양계에서 태양에 가장 가까운 행성은?",
    options: ["금성", "지구", "수성", "화성"],
    correctAnswer: 2,
    explanation: "수성은 태양계에서 태양에 가장 가까운 행성입니다.",
  },
  {
    id: 13,
    category: "과학",
    difficulty: "medium",
    question: "인체에서 가장 넓은 면적을 차지하는 장기는?",
    options: ["간", "피부", "폐", "심장"],
    correctAnswer: 1,
    explanation: "피부는 면적 기준으로 인체에서 가장 큰 장기입니다.",
  },
  {
    id: 14,
    category: "과학",
    difficulty: "medium",
    question: "진공 중 빛의 속도는 초당 약 몇 km인가?",
    options: ["약 3만 km", "약 30만 km", "약 300만 km", "약 3천 km"],
    correctAnswer: 1,
    explanation: "빛의 속도는 진공 중에서 초당 약 30만 km(정확히 299,792km)입니다.",
  },
  {
    id: 15,
    category: "과학",
    difficulty: "medium",
    question: "다음 중 DNA의 이중나선 구조를 처음 규명한 과학자는?",
    options: ["찰스 다윈", "제임스 왓슨", "알버트 아인슈타인", "그레고어 멘델"],
    correctAnswer: 1,
    explanation: "제임스 왓슨은 프랜시스 크릭과 함께 1953년 DNA 이중나선 구조를 밝혀냈습니다.",
  },
  {
    id: 16,
    category: "과학",
    difficulty: "easy",
    question: "원소기호 'O'가 나타내는 원소는?",
    options: ["금", "산소", "은", "철"],
    correctAnswer: 1,
    explanation: "O는 산소(Oxygen)의 원소기호입니다.",
  },
  {
    id: 17,
    category: "과학",
    difficulty: "easy",
    question: "건강한 성인의 정상 체온은 약 몇 도인가?",
    options: ["33.5도", "36.5도", "39.5도", "42.5도"],
    correctAnswer: 1,
    explanation: "사람의 정상 체온은 평균적으로 약 36.5도입니다.",
  },
  {
    id: 18,
    category: "과학",
    difficulty: "medium",
    question: "식물 세포에서 광합성이 일어나는 세포 소기관은?",
    options: ["미토콘드리아", "엽록체", "핵", "리보솜"],
    correctAnswer: 1,
    explanation: "엽록체는 빛 에너지를 이용해 광합성을 수행하는 세포 소기관입니다.",
  },
  {
    id: 19,
    category: "과학",
    difficulty: "medium",
    question: "뉴턴이 정립한, 질량을 가진 물체 사이에 작용하는 힘에 관한 법칙은?",
    options: ["관성의 법칙", "만유인력의 법칙", "에너지 보존 법칙", "열역학 제2법칙"],
    correctAnswer: 1,
    explanation: "만유인력의 법칙은 아이작 뉴턴이 정립한 법칙으로, 질량을 가진 모든 물체 사이에 서로 끌어당기는 힘이 작용한다는 내용입니다.",
  },
  {
    id: 20,
    category: "과학",
    difficulty: "hard",
    question: "원자력 발전에서 에너지를 얻는 기본 원리는?",
    options: ["핵융합", "핵분열", "화학연소", "광전효과"],
    correctAnswer: 1,
    explanation: "현재 상용 원자력 발전은 우라늄 등의 원자핵이 쪼개지는 핵분열 반응을 이용합니다.",
  },
  {
    id: 51,
    category: "과학",
    difficulty: "medium",
    question: "성인 인체의 뼈는 총 몇 개인가?",
    options: ["206개", "186개", "226개", "246개"],
    correctAnswer: 0,
    explanation: "성인의 뼈는 총 206개로 구성되어 있습니다.",
  },
  {
    id: 52,
    category: "과학",
    difficulty: "easy",
    question: "원소기호 'Fe'가 나타내는 원소는?",
    options: ["금", "은", "철", "아연"],
    correctAnswer: 2,
    explanation: "Fe는 철(Ferrum)의 원소기호입니다.",
  },
  {
    id: 53,
    category: "과학",
    difficulty: "medium",
    question: "몸무게 기준으로, 현재까지 알려진 동물 중 가장 큰 동물은?",
    options: ["아프리카코끼리", "향유고래", "대왕오징어", "대왕고래"],
    correctAnswer: 3,
    explanation: "대왕고래(흰수염고래)는 몸무게 기준으로 지구상에 알려진 동물 중 가장 큰 동물입니다.",
  },
  {
    id: 54,
    category: "과학",
    difficulty: "easy",
    question: "태양계에서 가장 큰 행성은?",
    options: ["목성", "토성", "해왕성", "천왕성"],
    correctAnswer: 0,
    explanation: "목성은 태양계 행성 중 부피와 질량이 가장 큰 행성입니다.",
  },
  {
    id: 55,
    category: "과학",
    difficulty: "medium",
    question: "사람의 혈액에서 산소를 운반하는 역할을 하는 세포는?",
    options: ["백혈구", "혈소판", "적혈구", "림프구"],
    correctAnswer: 2,
    explanation: "적혈구는 헤모글로빈을 이용해 몸 곳곳에 산소를 운반합니다.",
  },
  {
    id: 56,
    category: "과학",
    difficulty: "medium",
    question: "뉴턴의 운동 법칙 중, 외부 힘이 작용하지 않으면 물체가 정지 또는 등속 직선 운동 상태를 유지한다는 법칙은?",
    options: ["가속도의 법칙", "작용 반작용의 법칙", "에너지 보존 법칙", "관성의 법칙"],
    correctAnswer: 3,
    explanation: "관성의 법칙(뉴턴 제1법칙)은 외부 힘이 없으면 물체가 현재의 운동 상태를 유지한다는 법칙입니다.",
  },
  {
    id: 57,
    category: "과학",
    difficulty: "easy",
    question: "표준 대기압에서 물이 어는 온도는 섭씨 몇 도인가?",
    options: ["0도", "-10도", "10도", "4도"],
    correctAnswer: 0,
    explanation: "표준 대기압에서 물의 어는점(빙점)은 섭씨 0도입니다.",
  },
  {
    id: 58,
    category: "과학",
    difficulty: "easy",
    question: "표준 대기압에서 물이 끓는 온도는 섭씨 몇 도인가?",
    options: ["80도", "90도", "100도", "120도"],
    correctAnswer: 2,
    explanation: "표준 대기압에서 물의 끓는점은 섭씨 100도입니다.",
  },
  {
    id: 59,
    category: "과학",
    difficulty: "medium",
    question: "세포에서 유전정보(DNA)가 저장되어 있는 소기관은?",
    options: ["미토콘드리아", "리보솜", "골지체", "핵"],
    correctAnswer: 3,
    explanation: "핵은 세포 내에서 DNA(유전정보)를 담고 있는 소기관입니다.",
  },
  {
    id: 60,
    category: "과학",
    difficulty: "hard",
    question: "수용액의 산성 또는 염기성 정도를 나타내는 지표는?",
    options: ["pH", "몰농도", "전기전도도", "이온화도"],
    correctAnswer: 0,
    explanation: "pH는 수용액의 수소이온농도를 바탕으로 산성·염기성 정도를 나타내는 지표입니다.",
  },

  // ===== 지리 =====
  {
    id: 21,
    category: "지리",
    difficulty: "easy",
    question: "대한민국의 수도는?",
    options: ["부산", "서울", "인천", "대전"],
    correctAnswer: 1,
    explanation: "서울특별시는 대한민국의 수도입니다.",
  },
  {
    id: 22,
    category: "지리",
    difficulty: "medium",
    question: "2024년 기준 세계에서 인구가 가장 많은 나라는?",
    options: ["중국", "인도", "미국", "인도네시아"],
    correctAnswer: 1,
    explanation: "유엔 발표에 따르면 2023년경 인도가 중국을 추월해 2024년 기준 세계 인구 1위 국가입니다.",
  },
  {
    id: 23,
    category: "지리",
    difficulty: "easy",
    question: "대한민국(남한) 영토에서 가장 높은 산은?",
    options: ["지리산", "설악산", "한라산", "북한산"],
    correctAnswer: 2,
    explanation: "한라산(1,947m)은 남한 지역 기준으로 대한민국에서 가장 높은 산입니다. (한반도 전체 기준으로는 백두산이 가장 높습니다.)",
  },
  {
    id: 24,
    category: "지리",
    difficulty: "medium",
    question: "면적 기준으로 세계에서 가장 큰 대륙은?",
    options: ["아프리카", "아시아", "북아메리카", "유럽"],
    correctAnswer: 1,
    explanation: "아시아는 면적 기준으로 세계에서 가장 큰 대륙입니다.",
  },
  {
    id: 25,
    category: "지리",
    difficulty: "easy",
    question: "프랑스의 수도는?",
    options: ["런던", "베를린", "파리", "로마"],
    correctAnswer: 2,
    explanation: "파리는 프랑스의 수도입니다.",
  },
  {
    id: 26,
    category: "지리",
    difficulty: "medium",
    question: "사하라 사막이 위치한 대륙은?",
    options: ["아시아", "아프리카", "남아메리카", "오세아니아"],
    correctAnswer: 1,
    explanation: "사하라 사막은 아프리카 북부에 위치한 세계 최대의 열대 사막입니다.",
  },
  {
    id: 27,
    category: "지리",
    difficulty: "medium",
    question: "면적 기준으로 태평양과 대서양 중 더 넓은 바다는?",
    options: ["대서양", "태평양", "둘의 면적이 같다", "비교 불가능"],
    correctAnswer: 1,
    explanation: "태평양은 지구상에서 가장 넓은 대양입니다.",
  },
  {
    id: 28,
    category: "지리",
    difficulty: "easy",
    question: "일본의 수도는?",
    options: ["오사카", "교토", "도쿄", "삿포로"],
    correctAnswer: 2,
    explanation: "도쿄는 일본의 수도입니다.",
  },
  {
    id: 29,
    category: "지리",
    difficulty: "medium",
    question: "대한민국과 육상 국경을 맞대고 있는 유일한 나라는?",
    options: ["중국", "일본", "북한", "러시아"],
    correctAnswer: 2,
    explanation: "대한민국은 휴전선을 사이에 두고 북한과 육상 국경을 맞대고 있습니다.",
  },
  {
    id: 30,
    category: "지리",
    difficulty: "medium",
    question: "영토 면적 기준으로 세계에서 가장 넓은 나라는?",
    options: ["캐나다", "중국", "러시아", "미국"],
    correctAnswer: 2,
    explanation: "러시아는 영토 면적 기준 세계에서 가장 넓은 나라입니다.",
  },
  {
    id: 61,
    category: "지리",
    difficulty: "easy",
    question: "미국의 수도는?",
    options: ["워싱턴 D.C.", "뉴욕", "로스앤젤레스", "시카고"],
    correctAnswer: 0,
    explanation: "워싱턴 D.C.는 미국의 수도입니다. 뉴욕은 미국에서 인구가 가장 많은 도시일 뿐 수도가 아닙니다.",
  },
  {
    id: 62,
    category: "지리",
    difficulty: "easy",
    question: "영국의 수도는?",
    options: ["에든버러", "맨체스터", "리버풀", "런던"],
    correctAnswer: 3,
    explanation: "런던은 영국(그레이트브리튼 및 북아일랜드 연합왕국)의 수도입니다.",
  },
  {
    id: 63,
    category: "지리",
    difficulty: "medium",
    question: "해발고도 기준으로 세계에서 가장 높은 산은?",
    options: ["에베레스트산", "K2", "킬리만자로산", "몽블랑"],
    correctAnswer: 0,
    explanation: "에베레스트산(8,849m)은 해발고도 기준으로 세계에서 가장 높은 산입니다.",
  },
  {
    id: 64,
    category: "지리",
    difficulty: "medium",
    question: "오스트레일리아(호주)의 수도는?",
    options: ["시드니", "멜버른", "브리즈번", "캔버라"],
    correctAnswer: 3,
    explanation: "캔버라는 호주의 수도입니다. 시드니는 호주에서 인구가 가장 많은 도시일 뿐 수도가 아닙니다.",
  },
  {
    id: 65,
    category: "지리",
    difficulty: "medium",
    question: "캐나다의 수도는?",
    options: ["오타와", "토론토", "밴쿠버", "몬트리올"],
    correctAnswer: 0,
    explanation: "오타와는 캐나다의 수도입니다. 토론토는 캐나다에서 인구가 가장 많은 도시일 뿐 수도가 아닙니다.",
  },
  {
    id: 66,
    category: "지리",
    difficulty: "easy",
    question: "중국의 수도는?",
    options: ["상하이", "광저우", "홍콩", "베이징"],
    correctAnswer: 3,
    explanation: "베이징은 중국의 수도입니다. 상하이는 중국에서 인구·경제 규모가 가장 큰 도시일 뿐 수도가 아닙니다.",
  },
  {
    id: 67,
    category: "지리",
    difficulty: "medium",
    question: "면적 기준으로 세계에서 가장 작은 대륙은?",
    options: ["오세아니아", "유럽", "남극", "남아메리카"],
    correctAnswer: 0,
    explanation: "오세아니아는 면적 기준으로 일반적으로 분류되는 대륙 중 가장 작은 대륙입니다.",
  },
  {
    id: 68,
    category: "지리",
    difficulty: "hard",
    question: "대한민국 표준시(KST)의 기준이 되는 동경 경도는?",
    options: ["120도", "127도", "130도", "135도"],
    correctAnswer: 3,
    explanation: "대한민국 표준시는 동경 135도를 기준으로 UTC+9로 정해져 있습니다.",
  },
  {
    id: 69,
    category: "지리",
    difficulty: "medium",
    question: "스위스의 수도는?",
    options: ["베른", "취리히", "제네바", "바젤"],
    correctAnswer: 0,
    explanation: "베른은 스위스의 수도입니다. 취리히는 스위스에서 인구가 가장 많은 도시일 뿐 수도가 아닙니다.",
  },
  {
    id: 70,
    category: "지리",
    difficulty: "easy",
    question: "이탈리아의 수도는?",
    options: ["밀라노", "베네치아", "피렌체", "로마"],
    correctAnswer: 3,
    explanation: "로마는 이탈리아의 수도입니다.",
  },

  // ===== 스포츠 =====
  {
    id: 31,
    category: "스포츠",
    difficulty: "easy",
    question: "축구 한 팀의 경기 출전 인원(골키퍼 포함)은?",
    options: ["9명", "10명", "11명", "12명"],
    correctAnswer: 2,
    explanation: "축구는 골키퍼를 포함해 한 팀당 11명이 경기에 출전합니다.",
  },
  {
    id: 32,
    category: "스포츠",
    difficulty: "easy",
    question: "하계 올림픽은 몇 년마다 개최되는가?",
    options: ["2년", "3년", "4년", "5년"],
    correctAnswer: 2,
    explanation: "하계 올림픽은 원칙적으로 4년마다 개최됩니다.",
  },
  {
    id: 33,
    category: "스포츠",
    difficulty: "easy",
    question: "농구 한 팀의 코트 위 경기 인원은?",
    options: ["4명", "5명", "6명", "7명"],
    correctAnswer: 1,
    explanation: "농구는 한 팀당 5명이 코트 위에서 경기합니다.",
  },
  {
    id: 34,
    category: "스포츠",
    difficulty: "medium",
    question: "2002년 FIFA 월드컵을 공동 개최한 두 나라는?",
    options: ["한국과 중국", "한국과 일본", "일본과 중국", "한국과 미국"],
    correctAnswer: 1,
    explanation: "2002년 FIFA 월드컵은 대한민국과 일본이 공동으로 개최했습니다.",
  },
  {
    id: 35,
    category: "스포츠",
    difficulty: "medium",
    question: "야구에서 타자가 3번의 스트라이크를 당하면 무엇이 되는가?",
    options: ["볼넷", "삼진아웃", "홈런", "번트"],
    correctAnswer: 1,
    explanation: "스트라이크가 3번 선언되면 타자는 삼진아웃을 당합니다.",
  },
  {
    id: 36,
    category: "스포츠",
    difficulty: "easy",
    question: "태권도는 어느 나라에서 기원한 스포츠인가?",
    options: ["중국", "일본", "대한민국", "태국"],
    correctAnswer: 2,
    explanation: "태권도는 대한민국에서 기원한 무술이자 올림픽 정식 종목입니다.",
  },
  {
    id: 37,
    category: "스포츠",
    difficulty: "medium",
    question: "테니스에서 한 세트를 이기려면 일반적으로 몇 게임을 먼저 이겨야 하는가(2게임차 기준)?",
    options: ["4게임", "5게임", "6게임", "7게임"],
    correctAnswer: 2,
    explanation: "테니스는 일반적으로 상대보다 2게임 이상 앞서며 6게임을 먼저 이기면 한 세트를 승리합니다.",
  },
  {
    id: 38,
    category: "스포츠",
    difficulty: "medium",
    question: "2018년 동계올림픽이 개최된 대한민국의 도시는?",
    options: ["서울", "평창", "강릉", "인천"],
    correctAnswer: 1,
    explanation: "2018년 동계올림픽은 강원도 평창에서 개최되었습니다.",
  },
  {
    id: 39,
    category: "스포츠",
    difficulty: "easy",
    question: "배구 한 팀의 코트 위 경기 인원은?",
    options: ["5명", "6명", "7명", "8명"],
    correctAnswer: 1,
    explanation: "배구는 한 팀당 6명이 코트 위에서 경기합니다.",
  },
  {
    id: 40,
    category: "스포츠",
    difficulty: "medium",
    question: "공식 마라톤 경기의 거리는 약 몇 km인가?",
    options: ["30.195km", "35.195km", "42.195km", "50.195km"],
    correctAnswer: 2,
    explanation: "공식 마라톤 거리는 42.195km로 국제적으로 표준화되어 있습니다.",
  },
  {
    id: 71,
    category: "스포츠",
    difficulty: "medium",
    question: "골프에서 기준 타수(파)보다 1타 적게 홀을 마치는 것을 가리키는 용어는?",
    options: ["버디", "보기", "이글", "파"],
    correctAnswer: 0,
    explanation: "버디는 기준 타수보다 1타 적은 스코어로 홀을 마치는 것을 말합니다.",
  },
  {
    id: 72,
    category: "스포츠",
    difficulty: "easy",
    question: "야구에서 한 팀의 선발 수비 인원(투수 포함)은?",
    options: ["7명", "8명", "10명", "9명"],
    correctAnswer: 3,
    explanation: "야구는 투수를 포함해 한 팀당 9명이 수비 포지션에 나섭니다.",
  },
  {
    id: 73,
    category: "스포츠",
    difficulty: "easy",
    question: "얼음판 위에서 스톤을 미끄러뜨려 표적(하우스)에 맞추는 동계올림픽 정식 종목은?",
    options: ["컬링", "아이스하키", "봅슬레이", "스피드스케이팅"],
    correctAnswer: 0,
    explanation: "컬링은 얼음판 위에서 스톤을 미끄러뜨려 표적에 맞추는 동계올림픽 정식 종목입니다.",
  },
  {
    id: 74,
    category: "스포츠",
    difficulty: "medium",
    question: "태권도가 대한민국에서 기원한 것과 달리, 유도가 기원한 나라는?",
    options: ["중국", "브라질", "프랑스", "일본"],
    correctAnswer: 3,
    explanation: "유도는 일본의 가노 지고로가 19세기 말 창시한 무술입니다.",
  },
  {
    id: 75,
    category: "스포츠",
    difficulty: "hard",
    question: "야구에서 투수가 한 경기 동안 상대팀에게 안타를 하나도 허용하지 않고 완투로 승리하는 것을 가리키는 용어는?",
    options: ["노히트노런", "퍼펙트게임", "완봉승", "사이클링히트"],
    correctAnswer: 0,
    explanation: "노히트노런은 투수가 안타를 하나도 내주지 않고 완투 승리하는 것을 말합니다(볼넷·실책으로 인한 출루는 허용될 수 있습니다).",
  },
  {
    id: 76,
    category: "스포츠",
    difficulty: "medium",
    question: "배드민턴 공식 경기에서 한 세트는 몇 점을 먼저 획득하면 승리하는가(2점차 조건, 최대 30점 규정 기준)?",
    options: ["11점", "15점", "25점", "21점"],
    correctAnswer: 3,
    explanation: "배드민턴은 2점 차 조건으로 21점을 먼저 획득하면 한 세트를 승리하며, 최대 30점에서 세트가 종료됩니다.",
  },
  {
    id: 77,
    category: "스포츠",
    difficulty: "medium",
    question: "대한민국이 최초로 하계올림픽을 개최한 연도는?",
    options: ["1988년", "1986년", "2002년", "2018년"],
    correctAnswer: 0,
    explanation: "1988년 서울에서 대한민국 최초의 하계올림픽이 개최되었습니다.",
  },
  {
    id: 78,
    category: "스포츠",
    difficulty: "easy",
    question: "축구 경기의 정규 경기 시간(전반+후반, 연장전 제외)은 총 몇 분인가?",
    options: ["60분", "70분", "80분", "90분"],
    correctAnswer: 3,
    explanation: "축구의 정규 경기 시간은 전후반 각 45분씩 총 90분입니다.",
  },
  {
    id: 79,
    category: "스포츠",
    difficulty: "medium",
    question: "럭비(15인제 기준) 한 팀의 경기 인원은?",
    options: ["15명", "13명", "11명", "7명"],
    correctAnswer: 0,
    explanation: "15인제 럭비는 한 팀당 15명이 경기에 출전합니다. (13인제 리그럭비는 13명, 세븐스럭비는 7명입니다.)",
  },
  {
    id: 80,
    category: "스포츠",
    difficulty: "medium",
    question: "탁구(테이블테니스) 공식 경기에서 한 세트는 몇 점을 먼저 획득하면 승리하는가(2점차 조건 기준)?",
    options: ["15점", "21점", "5점", "11점"],
    correctAnswer: 3,
    explanation: "탁구는 2점 차 조건으로 11점을 먼저 획득하면 한 세트를 승리합니다.",
  },
];
